# Site settings: these are accessible via {{ site.title }} and so on.
title: Choreographic Programming
author: The Choreographic Programming Community
description: Resources and community around choreographic programming.

url: "https://choreographic-programming.github.io"

repo: "https://github.com/choreographic-programming/choreographic-programming.github.io"
github_user: "choreographic-programming"
github_repo: "choreographic-programming.github.io"

# google-analytics: UA-XXXXXXXXXX
# logo: "assets/img/logo/SRCC-square-red.png"
logo_pixels: 34
color: "#30638e"

markdown: kramdown
exclude: [_site, LICENSE, README.md, vendor, papers.bib, update.sh]
